<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Julia Nerenberg">
<meta name="dcterms.date" content="2024-05-05">
<meta name="description" content="In this blog post, I will further study optimal decision-making in the context of the the credit-risk prediction problem. My aim is to (a)determine a score function and threshold that maximize profit for the bank under more realistic assumptions and (b) assess which populations of prospective borrowers are most impacted by my proposed policy.">

<title>My Awesome CSCI 0451 Blog - ‘Optimal’ Decision-Making</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: white;
      }

      .quarto-title-block .quarto-title-banner {
        color: white;
background-image: url(../../img/landscape.png);
background-size: cover;
      }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">My Awesome CSCI 0451 Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">‘Optimal’ Decision-Making</h1>
                  <div>
        <div class="description">
          <p>In this blog post, I will further study optimal decision-making in the context of the the credit-risk prediction problem. My aim is to (a)determine a score function and threshold that maximize profit for the bank under more realistic assumptions and (b) assess which populations of prospective borrowers are most impacted by my proposed policy.</p>
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Julia Nerenberg </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 5, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="csci-0451-optimal-decision-making" class="level1">
<h1>CSCI 0451: ‘Optimal’ Decision Making</h1>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>This post explores the concept of ‘optimal’ decision making in the context of computer science. We will discuss the concept of ‘optimal’ and how it can affect the decision-making process. We will also explore some of the challenges and limitations of ‘optimal’ decision making in computer science.</p>
<p>I use a logistic regression model to predict whether a loan will be paid off or not. I then calculate a threshold for the model to maximize profit. I then use this threshold to make decisions on whether to lend money to a borrower or not.</p>
<p>To spoil the ending, with money-minded decision making, we were able to profit almost $3000 per loan. However, this doesn’t take into account any of ethical considerations that come with not lending money. This is a very important consideration to make when making decisions in the real world, as many decisions are not as simple as maximizing profit.</p>
<p>Let’s begin by grabbing the data:</p>
<div id="cell-3" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/PhilChodrow/ml-notes/main/data/credit-risk/train.csv"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>df_train <span class="op">=</span> pd.read_csv(url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exploring-the-data" class="level3">
<h3 class="anchored" data-anchor-id="exploring-the-data">Exploring the Data</h3>
<p>The first step is to look at the data: how it looks, what it contains, and initial observations. Lets take a look.</p>
<div id="cell-5" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data exploration</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df_train.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">person_age</th>
<th data-quarto-table-cell-role="th">person_income</th>
<th data-quarto-table-cell-role="th">person_home_ownership</th>
<th data-quarto-table-cell-role="th">person_emp_length</th>
<th data-quarto-table-cell-role="th">loan_intent</th>
<th data-quarto-table-cell-role="th">loan_grade</th>
<th data-quarto-table-cell-role="th">loan_amnt</th>
<th data-quarto-table-cell-role="th">loan_int_rate</th>
<th data-quarto-table-cell-role="th">loan_status</th>
<th data-quarto-table-cell-role="th">loan_percent_income</th>
<th data-quarto-table-cell-role="th">cb_person_default_on_file</th>
<th data-quarto-table-cell-role="th">cb_person_cred_hist_length</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>25</td>
<td>43200</td>
<td>RENT</td>
<td>NaN</td>
<td>VENTURE</td>
<td>B</td>
<td>1200</td>
<td>9.91</td>
<td>0</td>
<td>0.03</td>
<td>N</td>
<td>4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>27</td>
<td>98000</td>
<td>RENT</td>
<td>3.0</td>
<td>EDUCATION</td>
<td>C</td>
<td>11750</td>
<td>13.47</td>
<td>0</td>
<td>0.12</td>
<td>Y</td>
<td>6</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>22</td>
<td>36996</td>
<td>RENT</td>
<td>5.0</td>
<td>EDUCATION</td>
<td>A</td>
<td>10000</td>
<td>7.51</td>
<td>0</td>
<td>0.27</td>
<td>N</td>
<td>4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>24</td>
<td>26000</td>
<td>RENT</td>
<td>2.0</td>
<td>MEDICAL</td>
<td>C</td>
<td>1325</td>
<td>12.87</td>
<td>1</td>
<td>0.05</td>
<td>N</td>
<td>4</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>29</td>
<td>53004</td>
<td>MORTGAGE</td>
<td>2.0</td>
<td>HOMEIMPROVEMENT</td>
<td>A</td>
<td>15000</td>
<td>9.63</td>
<td>0</td>
<td>0.28</td>
<td>N</td>
<td>10</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-6" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df_train.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">person_age</th>
<th data-quarto-table-cell-role="th">person_income</th>
<th data-quarto-table-cell-role="th">person_emp_length</th>
<th data-quarto-table-cell-role="th">loan_amnt</th>
<th data-quarto-table-cell-role="th">loan_int_rate</th>
<th data-quarto-table-cell-role="th">loan_status</th>
<th data-quarto-table-cell-role="th">loan_percent_income</th>
<th data-quarto-table-cell-role="th">cb_person_cred_hist_length</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>26064.000000</td>
<td>2.606400e+04</td>
<td>25351.000000</td>
<td>26064.000000</td>
<td>23566.000000</td>
<td>26064.000000</td>
<td>26064.000000</td>
<td>26064.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>27.734385</td>
<td>6.597481e+04</td>
<td>4.783559</td>
<td>9569.468424</td>
<td>11.009372</td>
<td>0.217580</td>
<td>0.169970</td>
<td>5.794467</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>6.362612</td>
<td>6.330551e+04</td>
<td>4.166275</td>
<td>6297.660303</td>
<td>3.246762</td>
<td>0.412608</td>
<td>0.106491</td>
<td>4.055432</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>20.000000</td>
<td>4.000000e+03</td>
<td>0.000000</td>
<td>500.000000</td>
<td>5.420000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>2.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>23.000000</td>
<td>3.887250e+04</td>
<td>2.000000</td>
<td>5000.000000</td>
<td>7.900000</td>
<td>0.000000</td>
<td>0.090000</td>
<td>3.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>26.000000</td>
<td>5.500000e+04</td>
<td>4.000000</td>
<td>8000.000000</td>
<td>10.990000</td>
<td>0.000000</td>
<td>0.150000</td>
<td>4.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>30.000000</td>
<td>7.900000e+04</td>
<td>7.000000</td>
<td>12000.000000</td>
<td>13.470000</td>
<td>0.000000</td>
<td>0.230000</td>
<td>8.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>144.000000</td>
<td>6.000000e+06</td>
<td>123.000000</td>
<td>35000.000000</td>
<td>23.220000</td>
<td>1.000000</td>
<td>0.830000</td>
<td>30.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>First off, I’m very interested in the maximum age being 144. For the sake of my waning amusement, lets take a closer look at them.</p>
<div id="cell-8" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Entry with maximum person_age:</span><span class="ch">\n</span><span class="st">"</span>, df_train.loc[df_train[<span class="st">'person_age'</span>].idxmax()])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Entry with maximum person_age:
 person_age                        144
person_income                  250000
person_home_ownership            RENT
person_emp_length                 4.0
loan_intent                   VENTURE
loan_grade                          C
loan_amnt                        4800
loan_int_rate                   13.57
loan_status                         0
loan_percent_income              0.02
cb_person_default_on_file           N
cb_person_cred_hist_length          3
Name: 1561, dtype: object</code></pre>
</div>
</div>
<p>Fascinating! Moving on, let’s make some visualizations to better understand the data.</p>
<div id="cell-10" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># let's make some visualizations to better understand the data</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># histogram of person_age</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>plt.hist(df_train[<span class="st">'person_age'</span>], bins <span class="op">=</span> <span class="dv">20</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Person Age'</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Person Age'</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># histogram of person_income</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>plt.hist(df_train[<span class="st">'person_income'</span>], bins <span class="op">=</span> <span class="dv">20</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Person Income'</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Person Income'</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="co"># histogram of loan_int_rate</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>plt.hist(df_train[<span class="st">'loan_int_rate'</span>], bins <span class="op">=</span> <span class="dv">20</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Loan Interest Rate'</span>)</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Loan Interest Rate'</span>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a><span class="co"># histogram of loan_percent_income</span></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>plt.hist(df_train[<span class="st">'loan_percent_income'</span>], bins <span class="op">=</span> <span class="dv">20</span>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Loan Percent Income'</span>)</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Loan Percent Income'</span>)</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a><span class="co"># histogram of cb_person_cred_hist_length</span></span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>plt.hist(df_train[<span class="st">'cb_person_cred_hist_length'</span>], bins <span class="op">=</span> <span class="dv">20</span>)</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Credit History Length'</span>)</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Credit History Length'</span>)</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a><span class="co"># bar plot of loan_status</span></span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>df_train[<span class="st">'loan_status'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Loan Status'</span>)</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Bar Plot of Loan Status'</span>)</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a><span class="co"># bar plot of loan_intent</span></span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>df_train[<span class="st">'loan_intent'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Loan Intent'</span>)</span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Bar Plot of Loan Intent'</span>)</span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a><span class="co"># bar plot of person_home_ownership</span></span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>df_train[<span class="st">'person_home_ownership'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Home Ownership'</span>)</span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Bar Plot of Home Ownership'</span>)</span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a><span class="co"># bar plot of loan_grade</span></span>
<span id="cb6-61"><a href="#cb6-61" aria-hidden="true" tabindex="-1"></a>df_train[<span class="st">'loan_grade'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb6-62"><a href="#cb6-62" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Loan Grade'</span>)</span>
<span id="cb6-63"><a href="#cb6-63" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb6-64"><a href="#cb6-64" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Bar Plot of Loan Grade'</span>)</span>
<span id="cb6-65"><a href="#cb6-65" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-66"><a href="#cb6-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-67"><a href="#cb6-67" aria-hidden="true" tabindex="-1"></a><span class="co"># bar plot of cb_person_default_on_file</span></span>
<span id="cb6-68"><a href="#cb6-68" aria-hidden="true" tabindex="-1"></a>df_train[<span class="st">'cb_person_default_on_file'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb6-69"><a href="#cb6-69" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Default on File'</span>)</span>
<span id="cb6-70"><a href="#cb6-70" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb6-71"><a href="#cb6-71" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Bar Plot of Default on File'</span>)</span>
<span id="cb6-72"><a href="#cb6-72" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-73"><a href="#cb6-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-74"><a href="#cb6-74" aria-hidden="true" tabindex="-1"></a><span class="co"># bar plot of cb_person_cred_hist_length</span></span>
<span id="cb6-75"><a href="#cb6-75" aria-hidden="true" tabindex="-1"></a>df_train[<span class="st">'cb_person_cred_hist_length'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb6-76"><a href="#cb6-76" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Credit History Length'</span>)</span>
<span id="cb6-77"><a href="#cb6-77" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb6-78"><a href="#cb6-78" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Bar Plot of Credit History Length'</span>)</span>
<span id="cb6-79"><a href="#cb6-79" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-80"><a href="#cb6-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-81"><a href="#cb6-81" aria-hidden="true" tabindex="-1"></a><span class="co"># bar plot of person_emp_length</span></span>
<span id="cb6-82"><a href="#cb6-82" aria-hidden="true" tabindex="-1"></a>df_train[<span class="st">'person_emp_length'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb6-83"><a href="#cb6-83" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Employment Length'</span>)</span>
<span id="cb6-84"><a href="#cb6-84" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb6-85"><a href="#cb6-85" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Bar Plot of Employment Length'</span>)</span>
<span id="cb6-86"><a href="#cb6-86" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-87"><a href="#cb6-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-88"><a href="#cb6-88" aria-hidden="true" tabindex="-1"></a><span class="co"># bar plot of loan_amnt</span></span>
<span id="cb6-89"><a href="#cb6-89" aria-hidden="true" tabindex="-1"></a>df_train[<span class="st">'loan_amnt'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb6-90"><a href="#cb6-90" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Loan Amount'</span>)</span>
<span id="cb6-91"><a href="#cb6-91" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb6-92"><a href="#cb6-92" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Bar Plot of Loan Amount'</span>)</span>
<span id="cb6-93"><a href="#cb6-93" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-6-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-6-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-6-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-6-output-4.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-6-output-5.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-6-output-6.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-6-output-7.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-6-output-8.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-6-output-9.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-6-output-10.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-6-output-11.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-6-output-12.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-6-output-13.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>It seems that a lot of the data is concentrated around the mean. This is a good sign, as it means that the data is not too spread out. This will make it easier to analyze and make decisions based on general trends.</p>
<p>Since we are interested in determining the ‘optimal’ decision, we will need to define what ‘optimal’ means in this context. In the most simplified terms of loans, we want to minimize the risk of default while maximizing the return on investment. This is a classic trade-off problem in computer science, and we will need to balance these two objectives to make the ‘optimal’ decision. However, it is important to note that this is a gross generalization and not necessarily indicative of individual cases.</p>
</section>
<section id="building-a-model" class="level3">
<h3 class="anchored" data-anchor-id="building-a-model">Building a Model</h3>
<p>To build a model, we will need to define the features and labels of the data. The features are the attributes of the data that we will use to make predictions, excluding loan_garde, while the labels are the outcomes that we are trying to predict. In this case, the features are the attributes of the loans, such as the loan amount, interest rate, and term length, while the labels are the outcomes of the loans, such as whether the loan was repaid or defaulted.</p>
<p>We will use a Logistic Regression model to do this. Lets try to train the model on all of the attributes excluding loan_grade and loan_status and see how well it performs.</p>
<div id="cell-13" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We will use a Logistic Regression model to do this. Lets try to train the model on all of the attributes excluding loan_grade and loan_status and see how well it performs.</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> df_train</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># drop loan_grade</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> X_train.drop([<span class="st">'loan_grade'</span>], axis <span class="op">=</span> <span class="dv">1</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># drop loan_status</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> X_train.drop([<span class="st">'loan_status'</span>], axis <span class="op">=</span> <span class="dv">1</span>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>X_train.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">person_age</th>
<th data-quarto-table-cell-role="th">person_income</th>
<th data-quarto-table-cell-role="th">person_home_ownership</th>
<th data-quarto-table-cell-role="th">person_emp_length</th>
<th data-quarto-table-cell-role="th">loan_intent</th>
<th data-quarto-table-cell-role="th">loan_amnt</th>
<th data-quarto-table-cell-role="th">loan_int_rate</th>
<th data-quarto-table-cell-role="th">loan_percent_income</th>
<th data-quarto-table-cell-role="th">cb_person_default_on_file</th>
<th data-quarto-table-cell-role="th">cb_person_cred_hist_length</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>25</td>
<td>43200</td>
<td>RENT</td>
<td>NaN</td>
<td>VENTURE</td>
<td>1200</td>
<td>9.91</td>
<td>0.03</td>
<td>N</td>
<td>4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>27</td>
<td>98000</td>
<td>RENT</td>
<td>3.0</td>
<td>EDUCATION</td>
<td>11750</td>
<td>13.47</td>
<td>0.12</td>
<td>Y</td>
<td>6</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>22</td>
<td>36996</td>
<td>RENT</td>
<td>5.0</td>
<td>EDUCATION</td>
<td>10000</td>
<td>7.51</td>
<td>0.27</td>
<td>N</td>
<td>4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>24</td>
<td>26000</td>
<td>RENT</td>
<td>2.0</td>
<td>MEDICAL</td>
<td>1325</td>
<td>12.87</td>
<td>0.05</td>
<td>N</td>
<td>4</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>29</td>
<td>53004</td>
<td>MORTGAGE</td>
<td>2.0</td>
<td>HOMEIMPROVEMENT</td>
<td>15000</td>
<td>9.63</td>
<td>0.28</td>
<td>N</td>
<td>10</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-14" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># one-hot encode the categorical variables</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> pd.get_dummies(X_train)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>X_train.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">person_age</th>
<th data-quarto-table-cell-role="th">person_income</th>
<th data-quarto-table-cell-role="th">person_emp_length</th>
<th data-quarto-table-cell-role="th">loan_amnt</th>
<th data-quarto-table-cell-role="th">loan_int_rate</th>
<th data-quarto-table-cell-role="th">loan_percent_income</th>
<th data-quarto-table-cell-role="th">cb_person_cred_hist_length</th>
<th data-quarto-table-cell-role="th">person_home_ownership_MORTGAGE</th>
<th data-quarto-table-cell-role="th">person_home_ownership_OTHER</th>
<th data-quarto-table-cell-role="th">person_home_ownership_OWN</th>
<th data-quarto-table-cell-role="th">person_home_ownership_RENT</th>
<th data-quarto-table-cell-role="th">loan_intent_DEBTCONSOLIDATION</th>
<th data-quarto-table-cell-role="th">loan_intent_EDUCATION</th>
<th data-quarto-table-cell-role="th">loan_intent_HOMEIMPROVEMENT</th>
<th data-quarto-table-cell-role="th">loan_intent_MEDICAL</th>
<th data-quarto-table-cell-role="th">loan_intent_PERSONAL</th>
<th data-quarto-table-cell-role="th">loan_intent_VENTURE</th>
<th data-quarto-table-cell-role="th">cb_person_default_on_file_N</th>
<th data-quarto-table-cell-role="th">cb_person_default_on_file_Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>25</td>
<td>43200</td>
<td>NaN</td>
<td>1200</td>
<td>9.91</td>
<td>0.03</td>
<td>4</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>27</td>
<td>98000</td>
<td>3.0</td>
<td>11750</td>
<td>13.47</td>
<td>0.12</td>
<td>6</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>22</td>
<td>36996</td>
<td>5.0</td>
<td>10000</td>
<td>7.51</td>
<td>0.27</td>
<td>4</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>24</td>
<td>26000</td>
<td>2.0</td>
<td>1325</td>
<td>12.87</td>
<td>0.05</td>
<td>4</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>29</td>
<td>53004</td>
<td>2.0</td>
<td>15000</td>
<td>9.63</td>
<td>0.28</td>
<td>10</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-15" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># encode true/false columns as 1/0</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>X_train[<span class="st">'person_home_ownership_MORTGAGE'</span>] <span class="op">=</span> X_train[<span class="st">'person_home_ownership_MORTGAGE'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>X_train[<span class="st">'person_home_ownership_OTHER'</span>] <span class="op">=</span> X_train[<span class="st">'person_home_ownership_OTHER'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>X_train[<span class="st">'person_home_ownership_OWN'</span>] <span class="op">=</span> X_train[<span class="st">'person_home_ownership_OWN'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>X_train[<span class="st">'person_home_ownership_RENT'</span>] <span class="op">=</span> X_train[<span class="st">'person_home_ownership_RENT'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>X_train[<span class="st">'loan_intent_DEBTCONSOLIDATION'</span>] <span class="op">=</span> X_train[<span class="st">'loan_intent_DEBTCONSOLIDATION'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>X_train[<span class="st">'loan_intent_EDUCATION'</span>] <span class="op">=</span> X_train[<span class="st">'loan_intent_EDUCATION'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>X_train[<span class="st">'loan_intent_HOMEIMPROVEMENT'</span>] <span class="op">=</span> X_train[<span class="st">'loan_intent_HOMEIMPROVEMENT'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>X_train[<span class="st">'loan_intent_MEDICAL'</span>] <span class="op">=</span> X_train[<span class="st">'loan_intent_MEDICAL'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>X_train[<span class="st">'loan_intent_PERSONAL'</span>] <span class="op">=</span> X_train[<span class="st">'loan_intent_PERSONAL'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>X_train[<span class="st">'loan_intent_VENTURE'</span>] <span class="op">=</span> X_train[<span class="st">'loan_intent_VENTURE'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>X_train[<span class="st">'cb_person_default_on_file_N'</span>] <span class="op">=</span> X_train[<span class="st">'cb_person_default_on_file_N'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>X_train[<span class="st">'cb_person_default_on_file_Y'</span>] <span class="op">=</span> X_train[<span class="st">'cb_person_default_on_file_Y'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="co"># drop NAs</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> X_train.dropna()</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>X_train.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">person_age</th>
<th data-quarto-table-cell-role="th">person_income</th>
<th data-quarto-table-cell-role="th">person_emp_length</th>
<th data-quarto-table-cell-role="th">loan_amnt</th>
<th data-quarto-table-cell-role="th">loan_int_rate</th>
<th data-quarto-table-cell-role="th">loan_percent_income</th>
<th data-quarto-table-cell-role="th">cb_person_cred_hist_length</th>
<th data-quarto-table-cell-role="th">person_home_ownership_MORTGAGE</th>
<th data-quarto-table-cell-role="th">person_home_ownership_OTHER</th>
<th data-quarto-table-cell-role="th">person_home_ownership_OWN</th>
<th data-quarto-table-cell-role="th">person_home_ownership_RENT</th>
<th data-quarto-table-cell-role="th">loan_intent_DEBTCONSOLIDATION</th>
<th data-quarto-table-cell-role="th">loan_intent_EDUCATION</th>
<th data-quarto-table-cell-role="th">loan_intent_HOMEIMPROVEMENT</th>
<th data-quarto-table-cell-role="th">loan_intent_MEDICAL</th>
<th data-quarto-table-cell-role="th">loan_intent_PERSONAL</th>
<th data-quarto-table-cell-role="th">loan_intent_VENTURE</th>
<th data-quarto-table-cell-role="th">cb_person_default_on_file_N</th>
<th data-quarto-table-cell-role="th">cb_person_default_on_file_Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>27</td>
<td>98000</td>
<td>3.0</td>
<td>11750</td>
<td>13.47</td>
<td>0.12</td>
<td>6</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>22</td>
<td>36996</td>
<td>5.0</td>
<td>10000</td>
<td>7.51</td>
<td>0.27</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>24</td>
<td>26000</td>
<td>2.0</td>
<td>1325</td>
<td>12.87</td>
<td>0.05</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>29</td>
<td>53004</td>
<td>2.0</td>
<td>15000</td>
<td>9.63</td>
<td>0.28</td>
<td>10</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>21</td>
<td>21700</td>
<td>2.0</td>
<td>5500</td>
<td>14.91</td>
<td>0.25</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-16" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># train the model</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose your features, estimate new ones if needed, and fit a score-based machine learning model to the data. My suggestion is LogisticRegression. Once you have fit a logistic regression model, the weight vector is stored as the attribute model.coef_.</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>Y_train <span class="op">=</span> df_train[<span class="st">'loan_status'</span>]</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>Y_train <span class="op">=</span> Y_train[X_train.index]</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LogisticRegression(max_iter <span class="op">=</span> <span class="dv">1000</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>model.fit(X_train, Y_train)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># get the weights</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> model.coef_</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> weights[<span class="dv">0</span>]</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>weights</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<pre><code>array([-6.36230941e-08, -4.05736686e-05, -2.49216289e-08,  1.06558109e-04,
        9.49857325e-08,  2.54996456e-09, -1.22515188e-08, -6.57168949e-09,
        5.82453376e-11, -3.93934560e-09,  8.07258494e-09,  2.68000657e-09,
       -3.01882534e-09,  1.83914839e-09,  1.33270518e-09, -1.41426169e-09,
       -3.79897794e-09, -9.65224646e-09,  7.27204165e-09])</code></pre>
</div>
</div>
<p>The weights tell us how much each feature contributes to the prediction. The larger the weight, the more important the feature is in determining the outcome. We can use these weights to make predictions on new data and determine the ‘optimal’ decision.</p>
<div id="cell-18" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># test the model with cross-validation</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> cross_val_score</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>cross_val_score(model, X_train, Y_train, cv <span class="op">=</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>array([0.80379747, 0.81209079, 0.82558393, 0.80571928, 0.80921196])</code></pre>
</div>
</div>
<p>The model seems to be performing well, with cross validation scores averaging to about 0.81. This is a good sign, but we need to now find a threshold to determine whether a loan should be approved or not. This is where the concept of ‘optimal’ decision making comes into play. There are two assumptions we should make to determine whether a loan should be approved or not:</p>
<p>The first is that the loan is repaid in full, and is represented by <span class="math inline">\(loan_amnt*(1 + 0.25*loan_int_rate)**10 - loan_amnt\)</span>. This assumes that the loan is repaid in full after 10 years, and that the lender is able to recover 25% of the loan amount as interest after paying employees and other expenses.</p>
<p>The second is that the loan is defaulted on, and is represented by <span class="math inline">\(loan_amnt*(1 + 0.25*loan_int_rate)**3 - 1.7*loan_amnt\)</span>. This assumes that the loan is defaulted on after 3 years, and that the lender is able to recover 30% of the loan amount.</p>
<p>We can use these two assumptions to determine the threshold for the ‘optimal’ decision. If the predicted outcome is greater than the threshold, then the loan should be approved, otherwise it should be rejected.</p>
<div id="cell-20" class="cell" data-execution_count="97">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># create functions to calculate profit and loss for an entry in the dataset</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> profitORloss(row):</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># access loan status from Y_train</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    loan_status <span class="op">=</span> Y_train.loc[row.name]</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># if loan_status is 0, calculate profit, else calculate loss</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> loan_status <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> row[<span class="st">'loan_amnt'</span>]<span class="op">*</span>(<span class="dv">1</span> <span class="op">+</span> <span class="fl">.25</span><span class="op">*</span>row[<span class="st">'loan_int_rate'</span>]<span class="op">*</span><span class="fl">0.01</span>)<span class="op">**</span><span class="dv">10</span> <span class="op">-</span> row[<span class="st">'loan_amnt'</span>]</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="op">-</span>(row[<span class="st">'loan_amnt'</span>]<span class="op">*</span>(<span class="dv">1</span> <span class="op">+</span> <span class="fl">.25</span><span class="op">*</span>row[<span class="st">'loan_int_rate'</span>]<span class="op">*</span><span class="fl">0.01</span>)<span class="op">*</span><span class="dv">3</span> <span class="op">-</span> <span class="fl">1.7</span><span class="op">*</span>row[<span class="st">'loan_amnt'</span>])</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate profit or loss for each entry in the dataset and add it to the new column 'profit_or_loss'</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>X_train[<span class="st">'profit_or_loss'</span>] <span class="op">=</span> X_train.<span class="bu">apply</span>(profitORloss, axis <span class="op">=</span> <span class="dv">1</span>)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>X_train.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="97">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">person_age</th>
<th data-quarto-table-cell-role="th">person_income</th>
<th data-quarto-table-cell-role="th">person_emp_length</th>
<th data-quarto-table-cell-role="th">loan_amnt</th>
<th data-quarto-table-cell-role="th">loan_int_rate</th>
<th data-quarto-table-cell-role="th">loan_percent_income</th>
<th data-quarto-table-cell-role="th">cb_person_cred_hist_length</th>
<th data-quarto-table-cell-role="th">person_home_ownership_MORTGAGE</th>
<th data-quarto-table-cell-role="th">person_home_ownership_OTHER</th>
<th data-quarto-table-cell-role="th">person_home_ownership_OWN</th>
<th data-quarto-table-cell-role="th">person_home_ownership_RENT</th>
<th data-quarto-table-cell-role="th">loan_intent_DEBTCONSOLIDATION</th>
<th data-quarto-table-cell-role="th">loan_intent_EDUCATION</th>
<th data-quarto-table-cell-role="th">loan_intent_HOMEIMPROVEMENT</th>
<th data-quarto-table-cell-role="th">loan_intent_MEDICAL</th>
<th data-quarto-table-cell-role="th">loan_intent_PERSONAL</th>
<th data-quarto-table-cell-role="th">loan_intent_VENTURE</th>
<th data-quarto-table-cell-role="th">cb_person_default_on_file_N</th>
<th data-quarto-table-cell-role="th">cb_person_default_on_file_Y</th>
<th data-quarto-table-cell-role="th">profit_or_loss</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>27</td>
<td>98000</td>
<td>3.0</td>
<td>11750</td>
<td>13.47</td>
<td>0.12</td>
<td>6</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>4613.567568</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>22</td>
<td>36996</td>
<td>5.0</td>
<td>10000</td>
<td>7.51</td>
<td>0.27</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>2044.334031</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>24</td>
<td>26000</td>
<td>2.0</td>
<td>1325</td>
<td>12.87</td>
<td>0.05</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>-1850.395625</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>29</td>
<td>53004</td>
<td>2.0</td>
<td>15000</td>
<td>9.63</td>
<td>0.28</td>
<td>10</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>4028.690420</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>21</td>
<td>21700</td>
<td>2.0</td>
<td>5500</td>
<td>14.91</td>
<td>0.25</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>-7765.037500</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-21" class="cell" data-execution_count="134">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># graphic of profit or loss for the entire dataset</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>plt.hist(X_train[<span class="st">'profit_or_loss'</span>], bins <span class="op">=</span> <span class="dv">20</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Profit or Loss'</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Profit or Loss'</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the total profit or loss for the entire dataset</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>total_profit_or_loss <span class="op">=</span> X_train[<span class="st">'profit_or_loss'</span>].<span class="bu">sum</span>()</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Total Profit or Loss: "</span>, total_profit_or_loss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-13-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display" data-execution_count="134">
<pre><code>-24572766.55886856</code></pre>
</div>
</div>
<p>Now we can see the profit (or lack thereof) of each loan. Based on these assumptions, we can determine the threshold <span class="math inline">\(t\)</span> for the ‘optimal’ decision, where if the profit is greater than <span class="math inline">\(t\)</span>, then the loan should be approved, otherwise it should be rejected. Now, lets graph the profit of each loan against different thresholds to determine the ‘optimal’ decision.</p>
<div id="cell-23" class="cell" data-execution_count="105">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Now we can see the profit (or lack thereof) of each loan. Based on these assumptions, we can determine the threshold $t$ for the 'optimal' decision, where if the profit is greater than $t$, then the loan should be approved, otherwise it should be rejected. Now, lets graph the profit of each loan against different thresholds to determine the 'optimal' decision.</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># find maximum profit</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>max_profit <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> t <span class="kw">in</span> np.linspace(<span class="op">-</span><span class="dv">5000</span>, <span class="dv">5000</span>, <span class="dv">100</span>):</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    profit <span class="op">=</span> X_train[<span class="st">'profit_or_loss'</span>]</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    profit <span class="op">=</span> profit[profit <span class="op">&gt;</span> t]</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    profit <span class="op">=</span> profit.<span class="bu">sum</span>()</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    plt.scatter(t, profit, color <span class="op">=</span> <span class="st">'blue'</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> profit <span class="op">&gt;</span> max_profit:</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>        max_profit <span class="op">=</span> profit</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>        max_t <span class="op">=</span> t</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Threshold'</span>)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Profit'</span>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Profit vs. Threshold'</span>)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the threshold at maximum profit</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>plt.axvline(x <span class="op">=</span> max_t, color <span class="op">=</span> <span class="st">'red'</span>)</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Threshold at maximum profit: "</span>, max_t)</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Maximum profit: "</span>, max_profit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Threshold at maximum profit:  -1262.6262626262628
Maximum profit:  50918882.99425644</code></pre>
</div>
</div>
<div id="cell-24" class="cell" data-execution_count="106">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add a new column 'decision' to the dataset</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>X_train[<span class="st">'decision'</span>] <span class="op">=</span> X_train[<span class="st">'profit_or_loss'</span>] <span class="op">&gt;</span> max_t</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>X_train.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="106">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">person_age</th>
<th data-quarto-table-cell-role="th">person_income</th>
<th data-quarto-table-cell-role="th">person_emp_length</th>
<th data-quarto-table-cell-role="th">loan_amnt</th>
<th data-quarto-table-cell-role="th">loan_int_rate</th>
<th data-quarto-table-cell-role="th">loan_percent_income</th>
<th data-quarto-table-cell-role="th">cb_person_cred_hist_length</th>
<th data-quarto-table-cell-role="th">person_home_ownership_MORTGAGE</th>
<th data-quarto-table-cell-role="th">person_home_ownership_OTHER</th>
<th data-quarto-table-cell-role="th">person_home_ownership_OWN</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">loan_intent_DEBTCONSOLIDATION</th>
<th data-quarto-table-cell-role="th">loan_intent_EDUCATION</th>
<th data-quarto-table-cell-role="th">loan_intent_HOMEIMPROVEMENT</th>
<th data-quarto-table-cell-role="th">loan_intent_MEDICAL</th>
<th data-quarto-table-cell-role="th">loan_intent_PERSONAL</th>
<th data-quarto-table-cell-role="th">loan_intent_VENTURE</th>
<th data-quarto-table-cell-role="th">cb_person_default_on_file_N</th>
<th data-quarto-table-cell-role="th">cb_person_default_on_file_Y</th>
<th data-quarto-table-cell-role="th">profit_or_loss</th>
<th data-quarto-table-cell-role="th">decision</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>27</td>
<td>98000</td>
<td>3.0</td>
<td>11750</td>
<td>13.47</td>
<td>0.12</td>
<td>6</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>4613.567568</td>
<td>True</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>22</td>
<td>36996</td>
<td>5.0</td>
<td>10000</td>
<td>7.51</td>
<td>0.27</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>2044.334031</td>
<td>True</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>24</td>
<td>26000</td>
<td>2.0</td>
<td>1325</td>
<td>12.87</td>
<td>0.05</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>-1850.395625</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>29</td>
<td>53004</td>
<td>2.0</td>
<td>15000</td>
<td>9.63</td>
<td>0.28</td>
<td>10</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>4028.690420</td>
<td>True</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>21</td>
<td>21700</td>
<td>2.0</td>
<td>5500</td>
<td>14.91</td>
<td>0.25</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>-7765.037500</td>
<td>False</td>
</tr>
</tbody>
</table>

<p>5 rows × 21 columns</p>
</div>
</div>
</div>
<p>With this threshold, we can now determine the ‘optimal’ decision for each loan. If the profit is greater than the threshold, then the loan should be approved, otherwise it should be rejected. Using that decision, we can determine the overall profit of the loans and evaluate the performance of the model.</p>
<div id="cell-26" class="cell" data-execution_count="136">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># With this threshold, we can now determine the 'optimal' decision for each loan. If the profit is greater than the threshold, then the loan should be approved, otherwise it should be rejected. Using that decision, we can determine the overall profit of the loans and evaluate the performance of the model.</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the overall profit of the loans</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>overall_profit <span class="op">=</span> X_train[<span class="st">'profit_or_loss'</span>][X_train[<span class="st">'decision'</span>]].<span class="bu">sum</span>()</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Overall Profit: "</span>, overall_profit)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate average profit per accepted loan</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>average_profit <span class="op">=</span> overall_profit<span class="op">/</span>X_train[<span class="st">'decision'</span>].<span class="bu">sum</span>()</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Average Profit per Accepted Loan: "</span>, average_profit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Overall Profit:  50918882.99425644
Average Profit per Accepted Loan:  2831.8159720959034</code></pre>
</div>
</div>
</section>
<section id="evaluating-the-money-making-model" class="level3">
<h3 class="anchored" data-anchor-id="evaluating-the-money-making-model">Evaluating the Money Making Model</h3>
<p>Now, lets evaluate the model on the test set to see how well it performs. We will use the threshold that we determined earlier to make predictions on the test set and evaluate the performance of the model.</p>
<div id="cell-28" class="cell" data-execution_count="121">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># test model on test data</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># load test data</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/PhilChodrow/ml-notes/main/data/credit-risk/test.csv"</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>df_test <span class="op">=</span> pd.read_csv(url)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># drop NAs</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>df_test <span class="op">=</span> df_test.dropna()</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>X_test, Y_test <span class="op">=</span> df_test.drop([<span class="st">'loan_status'</span>], axis <span class="op">=</span> <span class="dv">1</span>), df_test[<span class="st">'loan_status'</span>]</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co"># drop loan_grade</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>X_test <span class="op">=</span> X_test.drop([<span class="st">'loan_grade'</span>], axis <span class="op">=</span> <span class="dv">1</span>)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="co"># one-hot encode the categorical variables</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>X_test <span class="op">=</span> pd.get_dummies(X_test)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="co"># encode true/false columns as 1/0</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'person_home_ownership_MORTGAGE'</span>] <span class="op">=</span> X_test[<span class="st">'person_home_ownership_MORTGAGE'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'person_home_ownership_OTHER'</span>] <span class="op">=</span> X_test[<span class="st">'person_home_ownership_OTHER'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'person_home_ownership_OWN'</span>] <span class="op">=</span> X_test[<span class="st">'person_home_ownership_OWN'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'person_home_ownership_RENT'</span>] <span class="op">=</span> X_test[<span class="st">'person_home_ownership_RENT'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'loan_intent_DEBTCONSOLIDATION'</span>] <span class="op">=</span> X_test[<span class="st">'loan_intent_DEBTCONSOLIDATION'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'loan_intent_EDUCATION'</span>] <span class="op">=</span> X_test[<span class="st">'loan_intent_EDUCATION'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'loan_intent_HOMEIMPROVEMENT'</span>] <span class="op">=</span> X_test[<span class="st">'loan_intent_HOMEIMPROVEMENT'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'loan_intent_MEDICAL'</span>] <span class="op">=</span> X_test[<span class="st">'loan_intent_MEDICAL'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'loan_intent_PERSONAL'</span>] <span class="op">=</span> X_test[<span class="st">'loan_intent_PERSONAL'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'loan_intent_VENTURE'</span>] <span class="op">=</span> X_test[<span class="st">'loan_intent_VENTURE'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'cb_person_default_on_file_N'</span>] <span class="op">=</span> X_test[<span class="st">'cb_person_default_on_file_N'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'cb_person_default_on_file_Y'</span>] <span class="op">=</span> X_test[<span class="st">'cb_person_default_on_file_Y'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a><span class="co"># predict the loan status</span></span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>Y_pred <span class="op">=</span> model.predict(X_test)</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate accuracy</span></span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score</span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>accuracy_score(Y_test, Y_pred)</span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy of model: "</span>, accuracy_score(Y_test, Y_pred))</span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a><span class="co"># ...</span></span>
<span id="cb22-40"><a href="#cb22-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-41"><a href="#cb22-41" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate profit or loss for each entry in the dataset and add it to the new column 'profit_or_loss'</span></span>
<span id="cb22-42"><a href="#cb22-42" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> profitORloss2(row, loan_status):</span>
<span id="cb22-43"><a href="#cb22-43" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> loan_status <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb22-44"><a href="#cb22-44" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> row[<span class="st">'loan_amnt'</span>]<span class="op">*</span>(<span class="dv">1</span> <span class="op">+</span> <span class="fl">.25</span><span class="op">*</span>row[<span class="st">'loan_int_rate'</span>]<span class="op">*</span><span class="fl">0.01</span>)<span class="op">**</span><span class="dv">10</span> <span class="op">-</span> row[<span class="st">'loan_amnt'</span>]</span>
<span id="cb22-45"><a href="#cb22-45" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb22-46"><a href="#cb22-46" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="op">-</span>(row[<span class="st">'loan_amnt'</span>]<span class="op">*</span>(<span class="dv">1</span> <span class="op">+</span> <span class="fl">.25</span><span class="op">*</span>row[<span class="st">'loan_int_rate'</span>]<span class="op">*</span><span class="fl">0.01</span>)<span class="op">*</span><span class="dv">3</span> <span class="op">-</span> <span class="fl">1.7</span><span class="op">*</span>row[<span class="st">'loan_amnt'</span>])</span>
<span id="cb22-47"><a href="#cb22-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-48"><a href="#cb22-48" aria-hidden="true" tabindex="-1"></a><span class="co"># Reset the index of X_test</span></span>
<span id="cb22-49"><a href="#cb22-49" aria-hidden="true" tabindex="-1"></a>X_test.reset_index(drop<span class="op">=</span><span class="va">True</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb22-50"><a href="#cb22-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Reset the index of Y_test</span></span>
<span id="cb22-51"><a href="#cb22-51" aria-hidden="true" tabindex="-1"></a>Y_test.reset_index(drop<span class="op">=</span><span class="va">True</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb22-52"><a href="#cb22-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-53"><a href="#cb22-53" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'profit_or_loss_predicted'</span>] <span class="op">=</span> X_test.<span class="bu">apply</span>(<span class="kw">lambda</span> row: profitORloss2(row, Y_pred[row.name]), axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb22-54"><a href="#cb22-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-55"><a href="#cb22-55" aria-hidden="true" tabindex="-1"></a><span class="co"># add a new column 'decision' to the dataset</span></span>
<span id="cb22-56"><a href="#cb22-56" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'decision_from_predicted'</span>] <span class="op">=</span> X_test[<span class="st">'profit_or_loss_predicted'</span>] <span class="op">&gt;</span> max_t</span>
<span id="cb22-57"><a href="#cb22-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-58"><a href="#cb22-58" aria-hidden="true" tabindex="-1"></a>X_test.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy of model:  0.800383877159309</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="121">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">person_age</th>
<th data-quarto-table-cell-role="th">person_income</th>
<th data-quarto-table-cell-role="th">person_emp_length</th>
<th data-quarto-table-cell-role="th">loan_amnt</th>
<th data-quarto-table-cell-role="th">loan_int_rate</th>
<th data-quarto-table-cell-role="th">loan_percent_income</th>
<th data-quarto-table-cell-role="th">cb_person_cred_hist_length</th>
<th data-quarto-table-cell-role="th">person_home_ownership_MORTGAGE</th>
<th data-quarto-table-cell-role="th">person_home_ownership_OTHER</th>
<th data-quarto-table-cell-role="th">person_home_ownership_OWN</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">loan_intent_HOMEIMPROVEMENT</th>
<th data-quarto-table-cell-role="th">loan_intent_MEDICAL</th>
<th data-quarto-table-cell-role="th">loan_intent_PERSONAL</th>
<th data-quarto-table-cell-role="th">loan_intent_VENTURE</th>
<th data-quarto-table-cell-role="th">cb_person_default_on_file_N</th>
<th data-quarto-table-cell-role="th">cb_person_default_on_file_Y</th>
<th data-quarto-table-cell-role="th">profit_or_loss_actual</th>
<th data-quarto-table-cell-role="th">profit_or_loss_predicted</th>
<th data-quarto-table-cell-role="th">decision_from_predicted</th>
<th data-quarto-table-cell-role="th">decision_from_actual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>21</td>
<td>42000</td>
<td>5.0</td>
<td>1000</td>
<td>15.58</td>
<td>0.02</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>-1416.850000</td>
<td>465.367227</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>32</td>
<td>51000</td>
<td>2.0</td>
<td>15000</td>
<td>11.36</td>
<td>0.29</td>
<td>9</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>4847.780062</td>
<td>4847.780062</td>
<td>True</td>
<td>True</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>35</td>
<td>54084</td>
<td>2.0</td>
<td>3000</td>
<td>12.61</td>
<td>0.06</td>
<td>6</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1091.841800</td>
<td>1091.841800</td>
<td>True</td>
<td>True</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>28</td>
<td>66300</td>
<td>11.0</td>
<td>12000</td>
<td>14.11</td>
<td>0.15</td>
<td>6</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>-16869.900000</td>
<td>4972.214553</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>22</td>
<td>70550</td>
<td>0.0</td>
<td>7000</td>
<td>15.88</td>
<td>0.08</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>-9933.700000</td>
<td>3331.859215</td>
<td>True</td>
<td>False</td>
</tr>
</tbody>
</table>

<p>5 rows × 23 columns</p>
</div>
</div>
</div>
<div id="cell-29" class="cell" data-execution_count="128">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate profit on test data</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>profit <span class="op">=</span> X_test[<span class="st">'profit_or_loss_predicted'</span>]</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>profit <span class="op">=</span> profit[profit <span class="op">&gt;</span> max_t]</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>profit <span class="op">=</span> profit.<span class="bu">sum</span>()</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>profit</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate profit on test data if all loans are approved</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>profit_all_approved <span class="op">=</span> X_test[<span class="st">'profit_or_loss_predicted'</span>].<span class="bu">sum</span>()</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Profit if all loans are approved: "</span>, profit_all_approved)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate profit on test data if all loans are rejected</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>profit_all_rejected <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Profit if all loans are rejected: "</span>, profit_all_rejected)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate profit on test data if we use the model to make decisions</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>profit_model <span class="op">=</span> profit</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Profit if we use the model to make decisions: "</span>, profit_model)</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="co"># improvement in profit</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>improvement <span class="op">=</span> profit_model <span class="op">-</span> profit_all_approved</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Improvement in profit: "</span>, improvement)</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a><span class="co"># average profit per loan</span></span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>average_profit <span class="op">=</span> profit<span class="op">/</span><span class="bu">len</span>(X_test)</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Average profit per loan: "</span>, average_profit)</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a><span class="co"># confusion matrix</span></span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> confusion_matrix</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>confusion_matrix(Y_test, X_test[<span class="st">'decision_from_predicted'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Profit if all loans are approved:  9487460.66068708
Profit if all loans are rejected:  0
Profit if we use the model to make decisions:  16509810.33443708
Improvement in profit:  7022349.67375
Average profit per loan:  2880.7904963247393</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="128">
<pre><code>array([[  77, 4377],
       [ 210, 1067]], dtype=int64)</code></pre>
</div>
</div>
<p>Thats pretty sweet! We have an accuracy of 80% on the test set, which is pretty high. We also increased the projected profits from 9487460 to 16509810, which is a 7 million dollar increase. This is a significant improvement, and shows the power of ‘optimal’ decision making in money driven computer science. It was also interesting to look at the confusion matrix, which shows the number of true positives, true negatives, false positives, and false negatives. This can help us understand where the model is making mistakes and how we can improve it, however, I’m feeling pretty good about 7 million dollars.</p>
<p>Additionally, the average profit per loan actually increased in the test set, though only marginally. It went from 2832 to 2881, so 49 dollars. I guess the money business is booming!</p>
</section>
<section id="evaluating-the-model-morally" class="level3">
<h3 class="anchored" data-anchor-id="evaluating-the-model-morally">Evaluating the Model Morally</h3>
<p>Money is great, but now it is time to evaluate how the model might discriminate against certain groups. To do this, I will graph the distribution of rejected and accepted loans for different metrics. I will be attempting to answer 3 questions:</p>
<ol type="1">
<li><p>Is it more difficult for people in certain age groups to access credit under your proposed system?</p></li>
<li><p>Is it more difficult for people to get loans in order to pay for medical expenses? How does this compare with the actual rate of default in that group? What about people seeking loans for business ventures or education?</p></li>
<li><p>How does a person’s income level impact the ease with which they can access credit under your decision system?</p></li>
</ol>
<div id="cell-32" class="cell" data-execution_count="221">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Is it more difficult for people in certain age groups to access credit under your proposed system?</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the percentage of approved loans for each age</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>approvedByAge <span class="op">=</span> []</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">18</span>, <span class="dv">101</span>):</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    approvedByAge.append(X_test[<span class="st">'decision_from_predicted'</span>][X_test[<span class="st">'person_age'</span>] <span class="op">==</span> i].<span class="bu">sum</span>()<span class="op">/</span><span class="bu">len</span>(X_test[<span class="st">'decision_from_predicted'</span>][X_test[<span class="st">'person_age'</span>] <span class="op">==</span> i]))</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>actualByAge <span class="op">=</span> []</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># add Y_test to X_test</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'loan_status'</span>] <span class="op">=</span> <span class="bu">abs</span>(Y_test <span class="op">-</span><span class="dv">1</span>) </span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">18</span>, <span class="dv">101</span>):</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    actualByAge.append(X_test[<span class="st">'loan_status'</span>][X_test[<span class="st">'person_age'</span>] <span class="op">==</span> i].<span class="bu">sum</span>()<span class="op">/</span><span class="bu">len</span>(X_test[<span class="st">'loan_status'</span>][X_test[<span class="st">'person_age'</span>] <span class="op">==</span> i]))</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>plt.plot(<span class="bu">range</span>(<span class="dv">18</span>, <span class="dv">101</span>), approvedByAge, color <span class="op">=</span> <span class="st">'red'</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>plt.plot(<span class="bu">range</span>(<span class="dv">18</span>, <span class="dv">101</span>), actualByAge, color <span class="op">=</span> <span class="st">'blue'</span>)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Age'</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Predicted vs actual repayment rate'</span>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a><span class="co"># graph of difference between predicted and actual repayment rate by age</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>plt.plot(<span class="bu">range</span>(<span class="dv">18</span>, <span class="dv">101</span>), np.array(approvedByAge) <span class="op">-</span> np.array(actualByAge))</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Age'</span>)</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Difference between predicted and actual repayment rate'</span>)</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\julia\AppData\Local\Temp\ipykernel_3012\4166889995.py:5: RuntimeWarning: invalid value encountered in scalar divide
  approvedByAge.append(X_test['decision_from_predicted'][X_test['person_age'] == i].sum()/len(X_test['decision_from_predicted'][X_test['person_age'] == i]))
C:\Users\julia\AppData\Local\Temp\ipykernel_3012\4166889995.py:10: RuntimeWarning: invalid value encountered in scalar divide
  actualByAge.append(X_test['loan_status'][X_test['person_age'] == i].sum()/len(X_test['loan_status'][X_test['person_age'] == i]))</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-19-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-19-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>It seems like younger people are expected to default more often, which is why they are rejected more often. There is also an interesting trend where older aged individuals are more likely to have loans accepted that will default. I wonder if this is because they are likely to die prior to full repayment of the loan. The implications of this are interesting, as it could be seen as a form of discrimination against both younger and older individuals, even if it is based on data. Overall though, the model does a decent job of not completely rejecting any age group, which is a good sign.</p>
<div id="cell-34" class="cell" data-execution_count="231">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Is it more difficult for people to get loans in order to pay for medical expenses? How does this compare with the actual rate of default in that group? What about people seeking loans for business ventures or education?</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the percentage of approved loans for each loan intent</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>approvedByIntent <span class="op">=</span> []</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'loan_intent'</span>] <span class="op">=</span> df_test[<span class="st">'loan_intent'</span>]</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> intent <span class="kw">in</span> X_test[<span class="st">'loan_intent'</span>].unique():</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    approvedByIntent.append(X_test[<span class="st">'decision_from_predicted'</span>][X_test[<span class="st">'loan_intent'</span>] <span class="op">==</span> intent].<span class="bu">sum</span>()<span class="op">/</span><span class="bu">len</span>(X_test[<span class="st">'decision_from_predicted'</span>][X_test[<span class="st">'loan_intent'</span>] <span class="op">==</span> intent]))</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>actualByIntent <span class="op">=</span> []</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> intent <span class="kw">in</span> X_test[<span class="st">'loan_intent'</span>].unique():</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>    actualByIntent.append(X_test[<span class="st">'loan_status'</span>][X_test[<span class="st">'loan_intent'</span>] <span class="op">==</span> intent].<span class="bu">sum</span>()<span class="op">/</span><span class="bu">len</span>(X_test[<span class="st">'loan_status'</span>][X_test[<span class="st">'loan_intent'</span>] <span class="op">==</span> intent]))</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="co"># table of predicted vs actual repayment rate by loan intent</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame({<span class="st">'Loan Intent'</span>: X_test[<span class="st">'loan_intent'</span>].unique(), <span class="st">'Predicted Repayment Rate'</span>: approvedByIntent, <span class="st">'Actual Repayment Rate'</span>: actualByIntent})</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="co"># graph of predicted vs actual repayment rate by loan intent</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>plt.bar(X_test[<span class="st">'loan_intent'</span>].unique(), approvedByIntent, color <span class="op">=</span> <span class="st">'red'</span>)</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>plt.bar(X_test[<span class="st">'loan_intent'</span>].unique(), actualByIntent, color <span class="op">=</span> <span class="st">'blue'</span>)</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Loan Intent'</span>)</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation <span class="op">=</span> <span class="dv">45</span>)</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Predicted vs actual repayment rate'</span>)</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>plt.legend([<span class="st">'Approved'</span>, <span class="st">'Actual'</span>])</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Loan Intent  Predicted Repayment Rate  Actual Repayment Rate
0            VENTURE                  0.954988               0.765207
1          EDUCATION                  0.949564               0.804074
2            MEDICAL                  0.947368               0.767368
3    HOMEIMPROVEMENT                  0.947080               0.753650
4           PERSONAL                  0.944764               0.757192
5  DEBTCONSOLIDATION                  0.955112               0.812968</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-20-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>It seems like the loans for all of the different purposes are accepted at similar rates, which is a good sign. However, the actual default rates for each group are a little different. For medical expenses, model predicts that more of the loans will be repayed than they actually are. This is a good sign, but medical loans are still the third most likely to be denied but only the 4th most likely to default. However, the difference in approval for each group is not too large. Despite this, medical debt is undoubtedly a horrible burden upon those who are already suffering, and it is important to consider the additional human cost of denying these loans.</p>
<div id="cell-36" class="cell" data-execution_count="233">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How does a person’s income level impact the ease with which they can access credit under your decision system?</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># divide income into 10 bins</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>X_test[<span class="st">'income_bin'</span>] <span class="op">=</span> pd.qcut(X_test[<span class="st">'person_income'</span>], <span class="dv">10</span>, labels <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the percentage of approved loans for each income bin</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>approvedByIncome <span class="op">=</span> []</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>):</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    approvedByIncome.append(X_test[<span class="st">'decision_from_predicted'</span>][X_test[<span class="st">'income_bin'</span>] <span class="op">==</span> i].<span class="bu">sum</span>()<span class="op">/</span><span class="bu">len</span>(X_test[<span class="st">'decision_from_predicted'</span>][X_test[<span class="st">'income_bin'</span>] <span class="op">==</span> i]))</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>actualByIncome <span class="op">=</span> []</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>):</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>    actualByIncome.append(X_test[<span class="st">'loan_status'</span>][X_test[<span class="st">'income_bin'</span>] <span class="op">==</span> i].<span class="bu">sum</span>()<span class="op">/</span><span class="bu">len</span>(X_test[<span class="st">'loan_status'</span>][X_test[<span class="st">'income_bin'</span>] <span class="op">==</span> i]))</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a><span class="co"># table of predicted vs actual repayment rate by income bin</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame({<span class="st">'Income Bin'</span>: <span class="bu">range</span>(<span class="dv">10</span>), <span class="st">'Predicted Repayment Rate'</span>: approvedByIncome, <span class="st">'Actual Repayment Rate'</span>: actualByIncome})</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df)</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a><span class="co"># graph of predicted vs actual repayment rate by income bin</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>plt.bar(<span class="bu">range</span>(<span class="dv">10</span>), approvedByIncome, color <span class="op">=</span> <span class="st">'red'</span>)</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>plt.bar(<span class="bu">range</span>(<span class="dv">10</span>), actualByIncome, color <span class="op">=</span> <span class="st">'blue'</span>)</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Income Bin'</span>)</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Predicted vs actual repayment rate'</span>)</span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>plt.legend([<span class="st">'Approved'</span>, <span class="st">'Actual'</span>])</span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Income Bin  Predicted Repayment Rate  Actual Repayment Rate
0           0                  0.884692               0.516899
1           1                  0.874751               0.604374
2           2                  0.911439               0.789668
3           3                  0.937093               0.728850
4           4                  0.964215               0.807157
5           5                  0.966135               0.824701
6           6                  0.984344               0.835616
7           7                  0.979920               0.877510
8           8                  0.997984               0.893145
9           9                  1.000000               0.904573</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="'Optimal' Decision-Making_files/figure-html/cell-21-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>I am so proud of my model. It does a very good job of not discriminating based on income level, with lower level incomes actually having a larger disparity between accepted and defaulted loans than higher income levels. Interestingly, the model predicts that the different income levels have a somewhat similar default rate, while the actual default rate is much higher for lower income levels. This is bad from a money perspective, but good from a moral perspective, as it shows that the model is not discriminating based on income level. Additionally, while one could argue that money is being lost to the poorer individuals, this is still maximizing profit with the current threshold. So, I suppose it could be seen as profitable to be charitable, at least in this case.</p>
</section>
<section id="reflection" class="level3">
<h3 class="anchored" data-anchor-id="reflection">Reflection</h3>
<p>I was surprised by the level of relative fairness achieved by my model. It was able to maximize profit while not obviously discriminating based on age or income level. It is at least subtle, which is more than I can say for most people. I learned that thresholds are important in decision making, and that they can be used to determine the ‘optimal’ decision beyond predicting labels. I also learned that it is important to consider the ethical implications of decision making, and that profit is not the only consideration when making decisions.</p>
<p>In terms of further ethical considerations, medical expenses have high default rates. This may be due to the nature that those in medical debt may not recover, and thus may not be able to repay the loan. It bring us to the question of whether it is fair to make these loans more difficult to obtain. While I feel my model was relatively successful in not discriminating against those seeking medical loans, it is still important to consider the human cost of denying a single one of these loans. Even cosmetic surgeries can be life changing for some! In the end, we must decide what is fair.</p>
<p>Fairness is a two part decision here, as we must decide what is means to be fair as well as apply that definition to this particular instance. I believe that fair decision making means not making decisions on things which cannot be determined by the individual. Even though we live in a “pull yourself up by your bootstraps” society, most individuals are a product of their environments, and some boots don’t even have straps anymore! Further, many things are impacted by a combination of effort and luck. However, if we can determine what it means to have something be outside of an individual’s control, we can make reasonably fair decisions.</p>
<p>We must also consider the business cost of accepting medical loans. While humans are not numbers, the individuals who make up a business are. While profits in the current setting generally go straight to the top and most certainly do not drop in the fashion of trickle down economics, in a world where they did we would have to consider the cost of accepting these loans on those who give them out. On the flip side, an individual who is able to pay off a medical loan is likely to be a loyal customer in the future.</p>
<p>In conclusion, it is not fair for medical expenses to have higher rates of default than other loans, especially when old age, which also has a high rate of default via death, is not discriminated against. The <em>most</em> fair decision would be to de-profitize the medical industry, but that is a discussion for another day.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>